name: ecommerce_supbase
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  google_fonts: ^6.3.2
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  svg_image: ^0.0.5
  flutter_svg: ^2.2.1
  get: ^4.7.2
  shared_preferences: ^2.5.3
  lottie: ^3.3.2
  animate_do: ^4.2.0
  flutter_otp_text_field: ^1.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/



  fonts:
    # - family: Jannah
    #   fonts:
    #     - asset: assets/fonts/jannah.ttf
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 600

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

